#-------------------------------
# General Site Settings

title: Parth Patekar
description: Computer Scientist // Mathematician // HCI Researcher
email: parthpatekar1997@gmail.com

menu:
- {name: About Me, url: '#about-me'}
- {name: Research, url: '#research'}
- {name: Contact, url: '#contact'}


#-------------------------------
# About Section

blurb: >
  **Parth specializes in HCI and Machine Learning**. He works at Samsung R&D Bangalore as a Senior Engineer in Visual Intelligence R&D Team. He has experience working at HCI lab, University of Manitoba and Machine Translation and NLP Lab, IIIT-Hyderabad.

resume:
- {format: 'PDF', url: '/assets/Resume.pdf', tail: ''}


#-------------------------------
# Work Section
# Pad/Resize images: convert ${f} -channel rgba -alpha set -resize 600x340 -background 'rgba(100%,100%,100%,0.0)' -gravity center -extent 600x340 ${f}

projects:
- {name: 'Coming Soon!...Under review for CHI 2021',                                folder: 'proj-1', file: 'work/proj-1.html'}
- {name: 'Limb-O: real-time comparison and visualization of lower limb motions',    folder: 'proj-2', file: 'work/proj-2.html'}
- {name: 'Unsupervised Approach for Monitoring Satire on Social Media',             folder: 'proj-3', file: 'work/proj-3.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'github', link: 'https://github.com/parthpatekar/'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/parthpatekar/'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'


#-------------------------------
